---
- name: Installing Apache MSI
  hosts: all

  tasks:
    - name: Create directory structure
      win_file:
        path: C:\ansible_examples
        state: directory
    - name: Download the Apache installer
      win_get_url:
        url: http://10.236.223.242/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi

    - name: Install MSI
      win_package:
        path: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
