---
- name: run windows update on windows machines
  hosts: all
  garther_facts: false
  tasks:
  - name: perform updates
    win_updates:
     category_names:
       -SecurityUpdates
       -CriticalUpdates
       -UpdateRollups
     reboot: yes
     reboot_timeout: 3600
